### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by mamin27** [isemenkov/pascalutils#5]
During compilation I found this compilation issue:
Please could you fix it?
utils.result.pas(187,11) Error: Identifier not found "TErrorNotExistException"

Regards
Marian

**Comment by isemenkov** [comment]
Hello, @mamin27 !
Thank you for report! Fixed.

**Comment by mamin27** [comment]
Thanks I will check it.

**Comment by mamin27** [comment]
Thanks it works.

MM
